language: python
pyhton:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python3 manage.py test
deploy:
  provider: heroku
  api_key:
    secure: b0AGiRNBWfP02Pq31h/om+k1brZQJRXT42tnOHUhHIb2EpmYV/LHopjfIBErmx9uSEd2o34aQXaFggd4pYt4kEamoXhMtsyAzX7ViR8+JU4neRwTRQBQpPmXy/w7JYLtxfcKG6zp17mMk3IZX3e6L9KDOJ+zK9ZI2XEgHcGwBy9MTjpJOXB/RYZ2eyyy570GNHZKfl/lVOBucra33VrCmMzr+1ofM1oN4b46DGuBlGAGI09yVsaoJ5ZOOx6hiezqyTrKZQQSkNt7Q/nP1GNaty5S/A5RVRos3zAMGqEmqhT+iOB+AzStQDR+zKhDqjMXFoWs1oYbBwnaJVmD0aV5Cdxc5YV6p8K6EpS8wY5MlCoBpKncHJ357rFtIpewPHJt1SndBDIwJTCW+EgbQehTctdzg0o1OdeXwG3O1EHO794ofRvGwMnQmT3IPHvdS8Scux94+mve5Re3cqBdD7gP4aSbFJ1PWmoZqMdaeFhWorEzyKH9Us8Tx2ZnFDmcfbw04Q762W8xJJud+kaK9B6xkUZZPX9Nd4ewBuIUThTalnZzXOofUbDslDllp2Y+CChe7ji873ddsfpXx/XteWqTPMphRZOMkHVTZ87GAm2XjmD97QSLy1B42BJqObiQLkSJRAaVptaUuONj01upGsLBC2LKJU+hdRM/OwuB0oXop+A=
  app: curs-online-store
