# Generated by Django 2.2.4 on 2020-06-10 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default='Cash', max_length=4)),
                ('address', models.CharField(default='', max_length=150)),
                ('telephone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
